name: NodeJS CD

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Task

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build