name: NodeJS CD

on:
  release:
    types: [published]

jobs:

  test:
    uses: toddaa/pack45web/.github/workflows/ci.yaml@stuff

  build:
    name: Build Task

    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build